# Generated by Django 5.0.6 on 2024-07-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('telefono', models.TextField()),
                ('usuarioid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrador.usuario')),
            ],
        ),
    ]
