# Generated by Django 5.0.6 on 2024-07-02 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tocken', models.CharField(blank=True, max_length=200, null=True)),
                ('verificado', models.BooleanField()),
                ('direccion', models.TextField()),
                ('usuarioid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrador.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True)),
                ('productoid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.producto')),
                ('clienteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendiente', models.BooleanField()),
                ('fecha', models.DateField(auto_now=True)),
                ('clienteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True)),
                ('compraid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.compra')),
                ('productoid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.producto')),
            ],
        ),
    ]
